app_reserva_salas_cooperativas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("reservas/", include("reservas.urls")),
    path("", include("core.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from core.views import index

app_name = 'core'
urlpatterns = [
    path('', index, name='index')
]

reservas/urls.py
from django.urls import path

from reservas.views import UnidadesListView, SalaView, CalendarioView, ReservaFormView

app_name = 'reservas'
urlpatterns = [
    path('', UnidadesListView.as_view(), name='unidades'),
    path('unidade/sala/<slug>/', SalaView.as_view(), name='sala'),
    path('unidade/sala/<slug>/reservar/', ReservaFormView.as_view(), name='adicionar_reserva'),
    path('calendario/sala/<sala_slug>/<ano>/<semana>/', CalendarioView.as_view(), name='calendario_com_semana'),
]

user/urls.py
from django.urls import path

from user.views import login_view
from django.contrib.auth.views import LogoutView

app_name = 'user'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

core/models.py
from django.db import models


# Create your models here.

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def index(request):
    return redirect('reservas:unidades')

core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

  <title>{% block title %}HCC Salas Corporativas{% endblock %}</title>

  <!-- CSS adicional para fixar o footer e personalizar botões -->
  <style>
      * {
          --altura_footer: 75px;
      }

      body {
          min-height: 100vh;
      }

      .footer {
          position: fixed;
          left: 0;
          bottom: 0;
          width: 100%;
          background-color: #f5f5f5;
          color: black;
          height: var(--altura_footer);
          z-index: 2;
      }

      .btn-transparent {
          background: none;
          border: none;
          text-decoration: none;
          color: inherit;
          text-align: center;
          display: block;
          width: 100%;
      }

      .btn-transparent i {
          font-size: 1.5rem; /* Altere este valor para ajustar o tamanho do ícone */
          display: block;
      }

      .root {
          min-height: 100vh !important;
          display: flex;
          flex-direction: column;
          padding-top: 56px;
          padding-bottom: 75px;
      }
  </style>

  {% block extra_css %}{% endblock %}

</head>

<body>
<!-- header -->
<nav class="navbar navbar-light bg-light fixed-top">
  <div class="container">

    <div class="d-flex align-items-center">
      <img src="{% static 'core/images/hcc/logo.png' %}" alt="" width="70"
           class="d-inline-block align-text-top">
      <span class="ms-5">Reserva de salas</span>
    </div>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
         aria-expanded="false">
        <i class="bi bi-person-circle"></i>
      </a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'user:logout' %}">Sair</a></li>
      </ul>
    </div>

  </div>
</nav>

<!-- Conteúdo principal -->
<div class="root">
  <div class="row justify-content-center align-items-center flex-grow-1 mx-0">
    {% block content %}{% endblock %}
  </div>
</div>

<!-- Footer fixo com três botões -->
<div class="footer">
  <div class="container">
    {% block footer %}
      <div class="row text-center">
        <div class="col">
          <a href="#" class="btn btn-transparent">
            <i class="bi bi-house"></i>
            <span>Início</span>
          </a>
        </div>
        <div class="col">
          {% url 'reservas:adicionar_reserva' view.get_sala_slug as url_adicionar_reserva %}
          {# Botão deve desativar se estiver na mesma URL (Adicionar reserva) #}
          <a href="{{ url_adicionar_reserva }}?previous={{ request.path }}"
             class="btn btn-transparent {% if request.path == url_adicionar_reserva %}disabled{% endif %}">
            <i class="bi bi-calendar-event"></i>
            <span>Reservar</span>
          </a>
        </div>
        <div class="col">
          <a href="#" class="btn btn-transparent">
            <i class="bi bi-list"></i>
            <span>Menu</span>
          </a>
        </div>
      </div>
    {% endblock %}

  </div>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>

{% block extra_js %}{% endblock %}

</body>

</html>